CMovie/urls.py
from django.conf.urls import url, include

from Film import views

urlpatterns = [
    # url(r'^$', views.index),
    url(r'^cinema/', include('Cinema.urls', namespace='cinema')),
    url(r'^user/', include('User.urls', namespace='user')),
    url(r'^film/', include('Film.urls', namespace='film'))
]

DjangoMovie/DjangoMovie/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^cinema/', include('Cinema.urls', namespace='cinema')),
    url(r'^user/', include('User.urls', namespace='user')),
    url(r'^film/', include('Film.urls', namespace='film')),


]

Film/urls.py
from django.conf.urls import url
from Film import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^filmlist/$', views.filmlist, name='filmlist'),
    url(r'^flimlist/(?P<cid>\d+)/$', views.filmlist, name='filmlist'),
    url(r'^filmlist/(?P<cid>\d+)/(?P<ftype>\d+)/(?P<area>\d+)/(?P<year>\d+)/(?P<sort>\d+)/', views.filmlist,
        name='filmlist'),
    url(r'^filmdetail/(\d+)/$', views.filmdetail, name='filmdetail'),
    url(r'^cinemalist/$', views.cinemalist, name='cinemalist'),
    # url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^schedule/(?P<filmid>\d+)/$', views.schedule, name='schedule'),
    # url(r'^chooseskd/(\d+)/$',views.chooseskd,name='chooseskd'),
    url(r'^seat/(\d+)/$', views.seat, name='seat'),
    url(r'^search/$', views.search, name='search'),
    url(r'^ranking/$', views.ranking, name='ranking'),
    url(r'^ranking/(\d+)/$', views.ranking, name='ranking'),
    url(r'^test/$', views.test, name='test'),
]

User/urls.py
from django.conf.urls import url
from User import views

urlpatterns = [
    # 注册
    url(r'^register/$', views.register, name='register'),
    # 发送手机验证码
    url(r'^sendsms/$', views.sendsms, name='sendsms'),
    # 密码登录
    url(r'^login/$', views.login, name='login'),
    # 手机验证码登录
    url(r'^phonelogin/$', views.phonelogin, name='phonelogin'),
    # 退出登录
    url(r'^logout/$', views.logout, name='logout'),
    # 修改个人信息
    url(r'^myinfo/$', views.myinfo, name='myinfo'),
    # 上传头像
    url(r'^upload/$', views.upload, name='upload'),
    # 查看我的订单
    url(r'^myorder/$', views.myorder, name='myorder'),
    # 查看单笔订单详情
    url(r'^orderdetail/(\d+)/$', views.orderdetail, name='orderdetail'),
    # 订票
    url(r'^orderticket/$', views.orderticket, name='orderticket'),
    # 支付
    url(r'^payment/$', views.payment, name='payment'),
    # test
    url(r'^test/$', views.test, name='test'),
]
r'show/(?P<name>[a-z]+)/(?P<age>\d+)/$'

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<form action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
    user:<input type="text" name="user">
    password:<input type="password" name="password">
    <input type="submit">
</form>


</form>
{% for order in orders %}
    <div style="border:chartreuse 1px solid">
        <p>订单号：{{ order.order_num }}</p>
        <p>电影名称：{{ order.film_namech }}</p>
        <p>电影日期：{{ order.skd_date }}</p>
        <p>开始时间：{{ order.skd_starttime }}</p>
        <p>影厅名称：{{ order.hall_name }}</p>
        <p>座位：{{ order.order_seat1 }}{{ order.order_seat2 }}{{ order.order_seat3 }}{{ order.order_seat4 }}</p>
        <p>票价：{{ order.order_prices }}</p>
        <p>影院名称：{{ order.cinema_name }}</p>
        <p>影院地址：{{ order.cinema_addr}}</p>
        <p>影院电话：{{ order.cinema_phone }}</p>
    </div>
{% endfor %}
</body>

</html>

templates/电影-正在热映1.html
{% extends 'common/base.html' %}
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0024)https://maoyan.com/films -->
<html><!--<![endif]-->
<head>
    <title>{{ title }}</title>
    {% block css1 %}
        <link rel="stylesheet" href="/static/css/common.d0f96cc2.css">
        <link rel="stylesheet" href="/static/css/movie-list.22f5a22a.css">
        <style>
            a {
                text-decoration: none;
                color: black;
            }
        </style>
    {% endblock css1 %}

</head>
{% block nav %}
            <div class="nav">
                <ul class="navbar">
                    <li><a href="{% url 'film:index' %}" data-act="home-click">首页</a></li>
                    <li><a href="{% url 'film:filmlist' 0 0 0 0 1 %}" data-act="movies-click" class="active">电影</a></li>
{#                    <li><a href="{% url 'film:cinemalist' %}" data-act="cinemas-click">影院</a></li>#}
                    <li><a href="{% url 'film:schedule' 1 %}" data-act="cinemas-click">购票</a></li>
                    <li><a href="{% url 'film:ranking' 1 %}" data-act="board-click" >榜单</a></li>
                </ul>
            </div>
    {% endblock nav %}
<body>
{% block navigation %}
    <div class="subnav">
        <ul class="navbar">
            {% for nav in navs %}
                <li>
                    <a data-act="subnav-click" data-val="{subnavClick:7}"
                       href="{% url 'film:filmlist' forloop.counter0 %}"{% ifequal cid forloop.counter0 %}
                       class="active"{% endifequal %}>{{ nav }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock navigation %}
{% block content %}
    <div class="container" id="app">
        <div class="movies-channel">
            <div class="tags-panel">
                <ul class="tags-lines">
                    <li class="tags-line" data-val="{tagTypeName:&#39;cat&#39;}">
                        <div class="tags-title">类型 :</div>
                        <ul class="tags">
                            {% for t in types %}
                                <li {% ifequal ftype forloop.counter0 %}
                                    class="active"{% endifequal %} data-state-val="{{ t }}">
                                    <a data-act="tag-click" data-val="{{ forloop.counter }}"
                                       href="{% url 'film:filmlist' cid=cid ftype=forloop.counter0 area=area year=year sort=sort %};"
                                       style="cursor: default">{{ t }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="tags-line tags-line-border" data-val="{tagTypeName:&#39;source&#39;}">
                        <div class="tags-title">区域 :</div>
                        <ul class="tags">
                            {% for a in areas %}
                                <li {% ifequal area forloop.counter0 %}
                                    class="active" {% endifequal %}
                                    data-state-val="{ sourceTagName:&#39;全部&#39;}">
                                    <a data-act="tag-click" data-val="{{ a }}"
                                       href="{% url 'film:filmlist' cid=cid ftype=ftype area=forloop.counter0 year=year sort=sort %}"
                                       style="cursor: default">{{ a }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="tags-line tags-line-border" data-val="{tagTypeName:&#39;year&#39;}">
                        <div class="tags-title">年代 :</div>
                        <ul class="tags">
                            {% for y in years %}
                                <li {% ifequal year forloop.counter0 %}
                                    class="active" {% endifequal %} data-state-val="{{ forloop.counter }}">
                                    <a data-act="tag-click" data-val="{TagName:&#39;全部&#39;}"
                                       href="{% url 'film:filmlist' cid=cid ftype=ftype area=area year=forloop.counter0 sort=sort %};"
                                       style="cursor: default">{{ y }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="movies-panel">
                <div class="movies-sorter">
                    <div class="cat-sorter">
                        <ul>
                            <li>
                                <a href="{% url 'film:filmlist' cid=cid ftype=ftype area=area year=year sort=1 %}">
                                    <span class="sort-control-group" data-act="sort-click" data-val="{{ sort }}"
                                          style="cursor: default">
                                    <span class="sort-control sort-radio {% ifequal sort 1 %}sort-radio-checked{% endifequal %}"></span>
                                    <span class="sort-control-label">按热门排序</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'film:filmlist' cid=cid ftype=ftype area=area year=year sort=2 %}">
                                    <span class="sort-control-group" data-act="sort-click" data-val="{{ sort }}">
                                    <span class="sort-control sort-radio {% ifequal sort 2 %}sort-radio-checked{% endifequal %}"></span>
                                    <span class="sort-control-label">按时间排序</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'film:filmlist' cid=cid ftype=ftype area=area year=year sort=3 %}">
                                    <span class="sort-control-group" data-act="sort-click" data-val="{{ sort }}">
                                    <span class="sort-control sort-radio {% ifequal sort 3 %}sort-radio-checked{% endifequal %}"></span>
                                    <span class="sort-control-label">按评价排序</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="play-sorter">
                        <span class="sort-control-group" data-act="isplay-click" data-val="{isplay:1}"
                              data-href="?isPlay=1">
                          <span class="sort-control sort-checkbox"></span>
                          <span class="sort-control-label">可播放</span>
                        </span>
                    </div>
                </div>
                <dl class="movie-list">
                    {% for film in films %}
                        <dd>
                            <div class="movie-item">
                                <a href="{% url 'film:filmdetail' film.film_id %}" target="_blank" data-act="movie-click"
                                   data-val="{{ film.film_id }}">
                                    <div class="movie-poster">
                                        <img class="poster-default"
                                             src="{% static 'images/loading_2.e3d934bf.png' %}">
                                        <img src="{{ film.film_photo }}">
                                    </div>
                                </a>
                                <div class="channel-action channel-action-sale">
                                    <a>购票</a>
                                </div>
                                <div class="movie-ver"><i class="imax3d"></i></div>
                            </div>
                            <div class="channel-detail movie-item-title" title="{{ film.film_name }}">
                                <a href="{% url 'film:filmdetail' film.film_id %}" target="_blank" data-act="movies-click"
                                   data-val="{movieId:1211270}">{{ film.film_namech }}</a>
                            </div>
                            <div class="channel-detail channel-detail-orange">
                                <i class="integer">{{ film.filmpf.film_rating }}</i>
                            </div>
                        </dd>
                    {% endfor %}

                    <div class="movies-pager">


                        <ul class="list-pager">


                            <li class="active">
                                <a class="page_1" href="javascript:void(0);" style="cursor: default">1</a>

                            </li>
                            <li>
                                <a class="page_2" href="https://maoyan.com/films?offset=30">2</a>

                            </li>
                            <li>
                                <a class="page_3" href="https://maoyan.com/films?offset=60">3</a>

                            </li>
                            <li>
                                <a class="page_4" href="https://maoyan.com/films?offset=90">4</a>

                            </li>


                            <li><a class="page_2" href="https://maoyan.com/films?offset=30">下一页</a>
                            </li>
                        </ul>


                    </div>
                </dl>
            </div>
        </div>

    </div>
{% endblock content %}
{% block js %}
    <script crossorigin="anonymous" src="/static/js/owl_1.7.11.js"></script>
    <script>
        Owl.start({
            project: 'com.sankuai.movie.fe.mywww',
            pageUrl: location.href.split('?')[0].replace(/\/\d+/g, '/:id'),
            devMode: false
        })
    </script>
    <!--[if IE 8]><script crossorigin="anonymous" src="//s3plus.meituan.net/v1/mss_e2821d7f0cfe4ac1bf9202ecf9590e67/cdn-prod/file:5788b470/es5-shim.bbad933f.js"></script>
<![endif]-->
    <!--[if IE 8]><script crossorigin="anonymous" src="//s3plus.meituan.net/v1/mss_e2821d7f0cfe4ac1bf9202ecf9590e67/cdn-prod/file:5788b470/es5-sham.d6ea26f4.js"></script>
<![endif]-->
    <script crossorigin="anonymous" src="/static/js/common.5b26e1eb.js"></script>
    <script crossorigin="anonymous" src="/static/js/movie-list.8476c1d2.js"></script>

{% endblock js %}
</body>
</html>